version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      github-actions:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      npm-dependencies:
        patterns: ['*']
    ignore:
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
  - package-ecosystem: cargo
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      cargo-dependencies:
        patterns: ['*']
  - package-ecosystem: pip
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      python-dependencies:
        patterns: ['*']
