[test]
preload = ["./tests/dom-globals.ts", "./tests/setup.ts"]
exclude = ["dist/**", "node_modules/**", "coverage/**"]
mockClear = true
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageThreshold = { lines = 0.8, functions = 0.8, statements = 0.8 }
