name: Code Foundry

on:
  push:
    branches: [staging]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pull-requests: write
  packages: read
  security-events: write

jobs:
  release-pr:
    name: Release PR
    uses: 0xPlayerOne/code-foundry/.github/workflows/release-pr.yml@v0.27.1
    with:
      runner: ubuntu-slim
    secrets: inherit
